---
title: "Publications"
---

## Published Manuscripts

### 2025

|Research Publications                         |             DOI               |
|----------------------------------------------|-------------------------------|
Budtarad N, Ongphichetmehta T, Siritho S. Insights into neuromyelitis optica spectrum disorder and pregnancy from a single-center study in Thailand. Sci Rep. 2025;15(1):4011. Published 2025 Feb 1. |  [10.1038/s41598-025-88624-x](https://www.nature.com/articles/s41598-025-88624-x)

### 2024

|Research Publications                         |             DOI               |
|----------------------------------------------|-------------------------------|
|Intarakhao P, **Ongphichetmetha T**, et al. Rituximab in secondary progressive multiple sclerosis: a meta-analysis. Ann Clin Transl Neurol. Published online August 26, 2024.| [10.1002/acn3.52186](https://onlinelibrary.wiley.com/doi/10.1002/acn3.52186) |
|Apiraksattayakul N, **Ongphichetmetha T**, Maethasith I, et al. Cognitive performance in patients with neuromyelitis optica: clinical and imaging characteristics. Sci Rep. 2024;14(1):20201. Published 2024 Aug 30.| [10.1038/s41598-024-71176-x](https://www.nature.com/articles/s41598-024-71176-x) |
|Chayanopparat S, Jitprapaikulsan J, **Ongphichetmetha T**. Catastrophic tumefactive acute disseminated encephalomyelitis in patient with dengue virus: a case report. J Neurovirol. 2024;30(2):202-207.| [10.1007/s13365-024-01210-1](https://link.springer.com/article/10.1007/s13365-024-01210-1) |
|**Ongphichetmetha T**, Jitprapaikulsan J, Siritho S, et al. Efficacy and safety of rituximab in multiple sclerosis and neuromyelitis optica spectrum disorder. Sci Rep. 2024;14(1):3503. Published 2024 Feb 12.| [10.1038/s41598-024-53838-y](https://www.nature.com/articles/s41598-024-53838-y) |
|**Ongphichetmetha T**, Aungsumart S, Siritho S, et al. Tumefactive demyelinating lesions: a retrospective cohort study in Thailand. Sci Rep. 2024;14(1):1426. Published 2024 Jan 16.| [10.1038/s41598-024-52048-w](https://www.nature.com/articles/s41598-024-52048-w) |

### 2023

|Research Publications                         |             DOI               |
|----------------------------------------------|-------------------------------|
|**Ongphichetmetha T**, Thanapornsangsuth P, Luechaipanit W, et al. The Utility of Neurofilament Light Chain in Aetiologic Differentiation of Disorders of Consciousness. Brain communications. Oct 2023.| [10.1093/braincomms/fcad278](https://academic.oup.com/braincomms/article/5/6/fcad278/7321530) |
|Rattanathamsakul N, **Ongphichetmetha T**, Weerachotisakul P, et al. Lymphomatosis cerebri with coexistent anti-N-methyl D-aspartate receptor antibody: A case report. Neuropathology. 2023.| [10.1111/neup.12899](https://onlinelibrary.wiley.com/doi/abs/10.1111/neup.12899) |
|Wannaphut C, **Ongphichetmetha T**, Satiraphan P, et al. Familial Neuromyelitis Optica Spectrum Disorders: Case Series and Systematic Review. Mult Scler Relat Disord. 2023.| [j.msard.2023.104627](https://www.sciencedirect.com/science/article/abs/pii/S2211034823001311) |
|Rattanawong W, **Ongphichetmetha T**, Hemachudha T, et al. Neurofilament light is associated with clinical outcome and hemorrhagic transformation in moderate to severe ischemic stroke. J Cent Nerv Syst Dis. 2023| [10.1177/11795735221147212](https://journals.sagepub.com/doi/10.1177/11795735221147212?url_ver=Z39.88-2003&rfr_id=ori:rid:crossref.org&rfr_dat=cr_pub%20%200pubmed) |

----

## Book Chapters

**Ongphichetmetha T**, Phanthumchinda K. Persistent postural perceptual dizziness. Basic and Clinical Neuroscience Volume.13. Bangkok: Division of Neurology, Department of Medicine, Faculty of Medicine, Chulalongkorn University; 2021, 102-121.

----

## Academic Articles

**Ongphichetmetha T**, Jitprapaikulsan J. Myelin Oligodendrocyte Glycoprotein Associated Disease https://www.si.mahidol.ac.th/sirirajdoctor/article_detail.aspx?ID=1543  

**Ongphichetmetha T**. Case study for Natalizumab, published in MS Mind #6 NewsLetter (International Eisai MS Newsletter distributed in Asia pacific region)
